
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 29 18:04:12 GMT-03:00 2011
//----------------------------------------------------

package analisadorSintatico;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int OCL_BASIC_TYPE = 39;
  public static final int GE = 33;
  public static final int FOUR_POINTS = 17;
  public static final int XOR = 26;
  public static final int LPAREN = 9;
  public static final int INT = 42;
  public static final int PRE = 3;
  public static final int MINUS = 23;
  public static final int STAR = 20;
  public static final int RPAREN = 10;
  public static final int NOT = 28;
  public static final int AND = 24;
  public static final int LT = 30;
  public static final int POINTS = 16;
  public static final int OR = 25;
  public static final int BOOL = 44;
  public static final int IMPLIES = 27;
  public static final int DIV = 21;
  public static final int OCL_COLLECTION = 40;
  public static final int PLUS = 22;
  public static final int IF = 5;
  public static final int ID = 45;
  public static final int CONTEXT = 2;
  public static final int LE = 31;
  public static final int EOF = 0;
  public static final int POINT_POINT = 14;
  public static final int error = 1;
  public static final int SELF = 36;
  public static final int COMA = 15;
  public static final int OCL_SUPER_TYPE = 38;
  public static final int LCURLY = 11;
  public static final int PIPE = 13;
  public static final int EQ = 29;
  public static final int RCURLY = 12;
  public static final int ARROW = 19;
  public static final int ENDIF = 8;
  public static final int ELSE = 7;
  public static final int POST = 4;
  public static final int POINT = 18;
  public static final int FLOAT = 43;
  public static final int THEN = 6;
  public static final int NE = 34;
  public static final int STRING = 41;
  public static final int AROBAPRE = 35;
  public static final int GT = 32;
  public static final int RESULT = 37;
}

